--- #YAML:1.0
name:                Email-Address
version:             1.889
abstract:            RFC 2822 Address Parsing
license:             perl
author:              
    - Casey West <casey@geeknest.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
